### PR TITLE
*: add fips build support

### LINKED ISSUE #200: Add FIPS build support
# Development Task
Introduce an optional switch that enables ng-monitoring to turn on FIPS.

### PR DESCRIPTION
**Pull request by mornyx**
### What problem does this PR solve?

Issue Number: close #200

See https://github.com/pingcap/tidb/pull/47949 for more details.

### What is changed and how it works?

build:
```
ENABLE_FIPS=1 make
```

check:
```
go tool nm bin/ng-monitoring | grep boring
```

### CODE REVIEW

**Comment by mornyx** [comment]
Seems CI fails on TiKV heap profiling, any ideas to help fix it? cc @Connor1996

**Comment by Connor1996** [comment]
@mornyx It's because http server is not ready to served while scraper already begins working. Better to make sure `CreateMockProfileServer` is finished by a channel, then call `conprof.Init()`

**Review by overvenus — APPROVED** [review]
Thank you!

**Review by crazycs520 — APPROVED** [review]

**Review by breezewish — APPROVED** [review]

**Pull request merged**
