### PR TITLE
topsql: add test case for same ts but different scan type

### PR DESCRIPTION
**Pull request by zhongzc**
Signed-off-by: Zhenchi <zhongzc_arch@outlook.com>

### CODE REVIEW

**Comment by mornyx** [comment]
LGTM

**Comment by mornyx** [comment]
So we decided to depend on this behavior of VictoriaMetrics?

**Comment by zhongzc** [comment]
> So we decided to depend on this behavior of VictoriaMetrics?

Just add test cases for topsql query & store implementation. The result is expected. 

If a new implementation doesn't pass the test, it won't satisfy our spec.

**Review by crazycs520 — APPROVED** [review]

**Pull request merged**
